services:
  backend:
    build:
      context: ./
      dockerfile: dockerfile
    image: spinnerz/carol-lists-backend
    container_name: lists-be
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/list-randomizer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=talento12
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lists-network

  db:
    image: postgres:13.16
    container_name: lists-db
    restart: always
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: talento12
      POSTGRES_DB: list-randomizer
    networks:
      - lists-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  lists-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
